set nocompatible
filetype off

if $USER_VIM_ENABLE_PLUGINS == 'Y'
  set rtp+=~/.vim/bundle/Vundle.vim
  call vundle#begin()

  Plugin 'Valloric/YouCompleteMe'
  Plugin 'scrooloose/nerdtree'
  Plugin 'rust-lang/rust.vim'

  call vundle#end()
  filetype plugin indent on

  " let Vundle manage Vundle, required
  Plugin 'VundleVim/Vundle.vim'
endif

if $USER_VIM_LOAD_LOCAL_CFG == 'Y'
  set exrc
else
  set secure
endif

filetype plugin on
syntax on

colorscheme goodwolf

if has("unix")
  let vimdir = ".vim"
elseif has('win32') || has('win64')
  let vimdir = "vimfiles"
endif

if has('gui_running')
	" removes off tool and menu bars
	set guioptions -=m
	set guioptions -=T

	" removes scrolls
	set guioptions -=r
	set guioptions -=L

	" sets initial size of gvim window
	set lines=25 columns=95
else 
	set bg=dark
endif

set number
map <F2> :set relativenumber!<CR>

if has('win32') || has('win64')
	set guifont=IBM_Plex_Mono_Text:h9:cANSI:qDRAFT
elseif has('unix')
	set guifont=Ubuntu\ Mono\ 8
endif

set encoding=utf-8
set autoindent
set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch
set wildmenu
set linebreak

nnoremap <Up> gk
nnoremap <Down> gj

nnoremap k gk
nnoremap j gj

nnoremap <C-Up> 10gk
nnoremap <C-Down> 10gj

nnoremap <C-K> 10gk
nnoremap <C-J> 10gj

inoremap <C-k> <C-o>gk
inoremap <C-j> <C-o>gj

inoremap <C-Up> <C-o>10gk
inoremap <C-Down> <C-o>10gj

set guicursor=n-v-c-i:block-Cursor

highlight Cursor guifg=steelblue guibg=darkgrey
highlight iCursor guifg=steelblue guibg=darkgrey

set swapfile
if has('win32') || has('win64')
	set dir=%HOMEPATH%\vimtmp
	set belloff=all " dont beep
elseif has('unix')
	set dir=~/.vimtmp
endif

set completeopt=menuone,preview,noselect

"autocmd InsertEnter * let save_cwd = getcwd() | set autochdir
"autocmd InsertLeave * set noautochdir | execute 'cd' fnameescape(save_cwd)

set laststatus=2
set statusline=%<%f%m\ \[%{&ff}:%{&fenc}:%Y]\ %=\ %l\/%L\ :\ %c%V

set tags=./tags;
set path=.;

function! Gentags()
	!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .
endfunction

map ff :%!clang-format<CR>

" YCM
let g:ycm_auto_trigger = 0
let g:ycm_use_clangd = 0
"let g:ycm_clangd_uses_ycmd_caching = 0
"let g:ycm_clangd_binary_path = exepath("clangd")
nnoremap ygi :YcmCompleter GoToInclude<CR>
nnoremap ygf :YcmCompleter FixIt<CR>
nnoremap ygd :YcmCompleter GoToDefinitionElseDeclaration<CR>
nnoremap ygt :YcmCompleter GetType<CR>


let g:asyncrun_open = 0

set list lcs=trail:\·,tab:\|\ 

" Leave cursor line when leaving window
augroup CursorLine
  au!
  au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  au WinLeave * setlocal nocursorline
augroup END

" Set spell check for polish tex files
"au BufReadPost *.tex setlocal spell spelllang=pl
"
